import { readFileSync, writeFileSync } from "node:fs";
import { cases } from "./float64-cases.mjs";
import { runZ3 } from "./solver.mjs";

const verify = process.argv.slice(2).includes("--check");
if (process.argv.slice(2).some(arg => arg !== "--check")) throw new Error("Usage: node tools/generate-float64.mjs [--check]");
const fp = bits => "((_ to_fp 11 53) #x" + bits + ")";
const expressions = cases.map(test => "(fp." + test.op + " RNE " + fp(test.a) +
  (test.b ? " " + fp(test.b) : "") + ")");
const query = expressions.map(expr =>
  "(simplify (ite (fp.isNaN " + expr + ") #xffffffffffffffff (fp.to_ieee_bv " + expr + ")))"
).join("\n");
const answers = runZ3("(set-logic QF_FP)\n" + query + "\n").trim().split(/\r?\n/);
if (answers.length !== cases.length || answers.some(line => !/^#x[0-9a-f]{16}$/.test(line))) {
  throw new Error("Unexpected Z3 reference output:\n" + answers.join("\n"));
}
const operators = {add: "+", sub: "-", mul: "*", div: "/"};
const header = "// Generated by tools/generate-float64.mjs using Z3's IEEE FP theory.\n" +
  "// RNE; exact non-NaN encodings; NaN payload and flags are not checked.\n";
const tests = cases.map((test, index) => {
  const encoding = answers[index].slice(2);
  const isNaN = encoding === "ffffffffffffffff";
  const expression = test.op === "sqrt" ? "a.sqrt()" : "a " + operators[test.op] + " b";
  return '///|\ntest "' + test.name + '" {\n' +
    "  let a = 0x" + test.a + "UL.reinterpret_as_double()\n" +
    (test.b ? "  let b = 0x" + test.b + "UL.reinterpret_as_double()\n" : "") +
    "  let actual = " + expression + "\n" +
    (isNaN
      ? "  assert_true(@float64.matches(actual, AnyNaN))\n"
      : "  assert_eq(actual.reinterpret_as_uint64(), 0x" + encoding + "UL)\n") +
    "}\n";
}).join("\n");
const path = new URL("../runtime/float64/vectors_generated_test.mbt", import.meta.url);
const content = header + "\n" + tests;
if (verify) {
  if (readFileSync(path, "utf8") !== content) throw new Error("Stale vectors: run just vectors");
} else {
  writeFileSync(path, content);
}
console.log(cases.length + " binary64 reference cases " + (verify ? "verified" : "generated"));
