import { readFileSync, writeFileSync } from "node:fs";
import { formats, casesFor } from "./float-cases.mjs";
import { fpLiteral, referenceBits, referenceBools } from "./fp-reference.mjs";

const args = process.argv.slice(2);
if (args.some(arg => arg !== "--check")) throw new Error("Usage: node tools/generate-floats.mjs [--check]");
const verify = args.includes("--check");
const header = "// Generated by tools/generate-floats.mjs using Z3's IEEE FP theory.\n" +
  "// RNE; exact non-NaN encodings; NaN payload and flags are not checked.\n";
const operators = {add: "+", sub: "-", mul: "*", div: "/"};
const nativeInput = (width, bits) => width === 32
  ? "Float::reinterpret_from_uint(0x" + bits + "U)"
  : "0x" + bits + "UL.reinterpret_as_double()";
const assertion = (width, expression, expected) => expected === null
  ? "  assert_true(@float" + width + ".matches(" + expression + ", AnyNaN))\n"
  : "  assert_eq(" + expression + ".reinterpret_as_" + formats[width].uint + "(), 0x" + expected + formats[width].suffix + ")\n";
function save(path, content) {
  const url = new URL("../" + path, import.meta.url);
  if (verify) {
    if (readFileSync(url, "utf8") !== content) throw new Error("Stale FP vectors: run just vectors (" + path + ")");
  } else writeFileSync(url, content);
}

for (const width of [32, 64]) {
  const cases = casesFor(width);
  const expressions = cases.map(test => "(fp." + test.op + (test.op === "neg" || test.op === "abs" ? " " : " RNE ") +
    fpLiteral(width, test.a) + (test.b ? " " + fpLiteral(width, test.b) : "") + ")");
  const answers = referenceBits(width, expressions);
  const predicates = referenceBools(cases.flatMap(test => {
    const a = fpLiteral(width, test.a), b = fpLiteral(width, test.b ?? test.a);
    return ["(fp.isNaN " + a + ")", "(fp.isInfinite " + a + ")", "(fp.eq " + a + " " + b + ")", "(fp.lt " + a + " " + b + ")"];
  }));
  const tests = cases.map((test, index) => {
    const native = operators[test.op] ? "a " + operators[test.op] + " b" : test.op === "neg" ? "-a" : "a." + test.op + "()";
    const [nan, infinite, eq, less] = predicates.slice(index * 4, index * 4 + 4);
    return '///|\ntest "' + test.name + '" {\n' +
      "  let a = " + nativeInput(width, test.a) + "\n" +
      (test.b ? "  let b = " + nativeInput(width, test.b) + "\n" : "") +
      "  let actual = @float" + width + "." + test.op + "(a" + (test.b ? ", b" : "") + ")\n" +
      "  let native = " + native + "\n" +
      assertion(width, "actual", answers[index]) + assertion(width, "native", answers[index]) +
      "  assert_eq(@float" + width + ".is_nan(a), " + nan + ")\n" +
      "  assert_eq(@float" + width + ".is_infinite(a), " + infinite + ")\n" +
      "  assert_eq(@float" + width + ".eq(a, " + (test.b ? "b" : "a") + "), " + eq + ")\n" +
      "  assert_eq(@float" + width + ".less(a, " + (test.b ? "b" : "a") + "), " + less + ")\n" +
      (nan === "false" ? "  let roundtrip = @float" + width + ".from_bits(0x" + test.a + formats[width].suffix + ")\n" +
        "  assert_eq(@float" + width + ".to_bits(roundtrip), 0x" + test.a + formats[width].suffix + ")\n" : "") +
      "}\n";
  });
  save("runtime/float" + width + "/vectors_generated_test.mbt", header + "\n" + tests.join("\n"));
  console.log(cases.length + " binary" + width + " operation cases " + (verify ? "verified" : "generated"));
}

const conversions = [];
for (const source of [32, 64]) {
  const target = source === 32 ? 64 : 32;
  const inputs = [...Object.values(formats[source].bits), ...casesFor(source).filter(test => test.name.includes("sample")).slice(0, 8).map(test => test.a)];
  if (source === 64) inputs.push(
    "3ff0000010000000", "3ff0000010000001", "3ff000000fffffff", "3ff0000030000000", // f32 halfway cases
    "36a0000000000000", "3690000000000000", "b690000000000000", // f32 minimum subnormal and half of it
    "3810000000000000", "47efffffe0000000", "47f0000000000000", // f32 minimum normal, maximum finite, overflow
  );
  for (const bits of inputs) conversions.push({source, target, bits});
}
const conversionTests = [];
for (const target of [32, 64]) {
  const selected = conversions.filter(test => test.target === target);
  const {exponent, precision} = formats[target];
  const answers = referenceBits(target, selected.map(test => "((_ to_fp " + exponent + " " + precision + ") RNE " + fpLiteral(test.source, test.bits) + ")"));
  selected.forEach((test, index) => {
    const method = target === 32 ? "to_float" : "to_double";
    conversionTests.push('///|\ntest "binary' + test.source + ' to binary' + target + ' case ' + index + '" {\n' +
      "  let input = " + nativeInput(test.source, test.bits) + "\n" +
      "  let actual = @float" + test.source + "." + method + "(input)\n" +
      "  let native = " + (target === 32 ? "Float::from_double(input)" : "input.to_double()") + "\n" +
      assertion(target, "actual", answers[index]) + assertion(target, "native", answers[index]) + "}\n");
  });
}
save("runtime/float_conversions/vectors_generated_test.mbt", header + "\n" + conversionTests.join("\n"));
console.log(conversions.length + " precision conversion cases " + (verify ? "verified" : "generated"));
