import { readFileSync, writeFileSync } from "node:fs";
import { runZ3 } from "./solver.mjs";
import { integerCases, textCases } from "./runtime-cases.mjs";
import { encodeSmtText, decodeSmtText } from "./smt-text.mjs";

const args = process.argv.slice(2);
if (args.some(arg => arg !== "--check")) throw new Error("Usage: node tools/generate-runtime.mjs [--check]");
const verify = args.includes("--check");
const generated = new Map();
const header = "// Generated by tools/generate-runtime.mjs using Z3; do not edit.\n";
const hex = (value, width) => value.toString(16).padStart(width / 4, "0");

for (const width of [32, 64]) {
  const suffix = width === 32 ? "U" : "UL";
  const signed = width === 32 ? "int" : "int64";
  const unsigned = width === 32 ? "uint" : "uint64";
  const cases = integerCases(width);
  const operations = ["bvadd", "bvsub", "bvmul", "bvand", "bvor", "bvxor", "bvnot", "bvult", "bvslt", "bvshl", "bvlshr", "bvashr"];
  const expressions = cases.flatMap(({a, b, shift}) => {
    const x = "#x" + hex(a, width), y = "#x" + hex(b, width);
    return operations.map(op => "(" + op + " " + x +
      (op === "bvnot" ? "" : " " + (op.includes("sh") ? "#x" + hex(BigInt(shift), width) : y)) + ")");
  });
  const answers = runZ3("(set-logic QF_BV)\n" + expressions.map(expr => "(simplify " + expr + ")").join("\n")).trim().split(/\r?\n/);
  if (answers.length !== expressions.length) throw new Error("Wrong bitvector answer count");
  const tests = cases.map(({a, b, shift}, index) => {
    const expected = Object.fromEntries(operations.map((op, offset) => {
      const value = answers[index * operations.length + offset];
      if (op === "bvult" || op === "bvslt") {
        if (!/^(true|false)$/.test(value)) throw new Error("Invalid Bool reference: " + value);
        return [op, value];
      }
      if (!new RegExp("^#x[0-9a-f]{" + width / 4 + "}$").test(value)) throw new Error("Invalid BV reference: " + value);
      return [op, "0x" + value.slice(2) + suffix];
    }));
    const checks = [
      ["@uint" + width + ".add(a, b)", "bvadd"], ["a + b", "bvadd"],
      ["@uint" + width + ".sub(a, b)", "bvsub"], ["a - b", "bvsub"],
      ["a * b", "bvmul"], ["a & b", "bvand"], ["a | b", "bvor"],
      ["a ^ b", "bvxor"], ["a.lnot()", "bvnot"], ["a < b", "bvult"],
      ["@uint" + width + ".less(a, b)", "bvult"],
      ["sa < sb", "bvslt"], ["a << " + shift, "bvshl"], ["a >> " + shift, "bvlshr"],
      ["(sa >> " + shift + ").reinterpret_as_" + unsigned + "()", "bvashr"],
      ["(sa + sb).reinterpret_as_" + unsigned + "()", "bvadd"],
      ["(sa - sb).reinterpret_as_" + unsigned + "()", "bvsub"],
      ["(sa * sb).reinterpret_as_" + unsigned + "()", "bvmul"],
    ];
    return '///|\ntest "Z3 bitpattern ' + width + ' case ' + index + '" {\n' +
      "  let a = 0x" + hex(a, width) + suffix + "\n" +
      "  let b = 0x" + hex(b, width) + suffix + "\n" +
      "  let sa = a.reinterpret_as_" + signed + "()\n" +
      "  let sb = b.reinterpret_as_" + signed + "()\n" +
      checks.map(([expr, op]) => "  assert_eq(" + expr + ", " + expected[op] + ")\n").join("") + "}\n";
  });
  generated.set("runtime/uint" + width + "/vectors_generated_test.mbt", header + "// Shift counts are in [0, width); native overshifts are not SMT overshifts.\n\n" + tests.join("\n"));
}

// Escape every scalar explicitly, avoiding SMT quoting/backslash ambiguity.
const smtInt = value => value < 0 ? "(- " + -value + ")" : String(value);
const moonString = value => '"' + [...value].map(c => "\\u{" + c.codePointAt(0).toString(16) + "}").join("") + '"';
const queries = textCases.flatMap(({value, start, count}) => {
  const s = encodeSmtText(value);
  return ["(str.len " + s + ")", "(str.at " + s + " " + smtInt(start) + ")",
    "(str.substr " + s + " " + smtInt(start) + " " + smtInt(count) + ")"];
});
const answers = runZ3(queries.map(expr => "(simplify " + expr + ")").join("\n")).trim().split(/\r?\n/);
if (answers.length !== queries.length) throw new Error("Wrong string answer count");
const tests = textCases.map(({value, start, count}, index) => {
  const [length, charAt, substring] = answers.slice(index * 3, index * 3 + 3);
  if (!/^\d+$/.test(length)) throw new Error("Invalid string length: " + length);
  return '///|\ntest "Z3 Unicode case ' + index + '" {\n' +
    "  let text = @text.from_string(" + moonString(value) + ").unwrap()\n" +
    "  assert_eq(text.length(), " + length + ")\n" +
    "  assert_eq(text.char_at(" + start + ").to_string(), " + moonString(decodeSmtText(charAt)) + ")\n" +
    "  assert_eq(text.substring(" + start + ", " + count + ").to_string(), " + moonString(decodeSmtText(substring)) + ")\n" + "}\n";
});
generated.set("runtime/text/vectors_generated_test.mbt", header + "\n" + tests.join("\n"));

for (const [path, content] of generated) {
  const url = new URL("../" + path, import.meta.url);
  if (verify) {
    if (readFileSync(url, "utf8") !== content) throw new Error("Stale runtime vectors: run just vectors (" + path + ")");
  } else {
    writeFileSync(url, content);
  }
}
console.log("48 integer + " + textCases.length + " Unicode reference cases " + (verify ? "verified" : "generated"));
